version: "3"

services:
  suricata:
    container_name: suricata
    #image: pihole/pihole:latest
    network_mode: host
    environment:
     CONFIG="-i wlan0"   
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
