version: "3"

services:
  suricata:
    container_name: suricata
    image: suricata:v5
    network_mode: host
    environment:
      CONFIG: '-i eth1 -i eth2'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped
    volumes:
      - './logs:/var/log/suricata'


